### PR TITLE
Observers

### LINKED ISSUE #2: Add option to not fail the healthcheck response for certain dependencies
By default, any error occurring in the checker responses leads to a `503` HTTP status code. But we may not want to fail the healthcheck in case certain dependencies fail (eg: metrics service, s3 etc) but would like to observe the errors in the response for taking further action.

### PR DESCRIPTION
**Pull request by sponomarev**
Closes #2 

@karthikmuralidharan   The approach is very naive but it works and is extremely simple. Please, check it out.

### CODE REVIEW

**Comment by karthikmuralidharan** [comment]
@sponomarev  thanks, I like it!! It's clean and easy to read. Overall, LGTM. I've added one small comment (non-blocker).

File: health.go [hunk 1]
```diff
@@ -30,7 +31,11 @@ type (
 
 // Handler returns an http.Handler
 func Handler(opts ...Option) http.Handler {
-	h := &health{make(map[string]Checker)}
+	h := &health{
```
Comment (karthikmuralidharan) [inline health.go:34]: Since the initializations look the same, it might be more legible to add the fields for which the maps are being initialized. 

I'm actually not opinionated on this though since order needs to be guaranteed when fields are not specified. 

Thoughts ?

```
h := &health{
 		checkers:  make(map[string]Checker),
 		observers: make(map[string]Checker),
 	}
```

**Review by karthikmuralidharan — APPROVED** [review]

File: health.go (hunk 1 above)
Comment (sponomarev) [reply health.go:34]: @karthikmuralidharan Yeah, makes sense. I've changed it. Please, take a look.

**Review by karthikmuralidharan — APPROVED** [review]
LGTM
